version: '3'
services:
  redis:
    image: redis
  rabbit:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/pg_backups
    environment:
      - POSTGRES_USER=booktype
      - POSTGRES_PASSWORD=booktype
      - POSTGRES_DB=booktype
  web:
    build: web
    depends_on:
      - redis
      - rabbit
      - db
    links:
      - redis
      - rabbit
      - db
    volumes:
      - ./web/volumes/data:/code/mybook/data:rw
      - ./web/volumes/static:/code/mybook/static:rw
      - ./web/volumes/logs:/code/mybook/logs:rw
      - ./web/volumes/logs/supervisor:/var/log/supervisor:rw
      - ./web/volumes/logs/nginx:/var/log/nginx:rw
  proxy:
    image: nginx:mainline-alpine
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
     - web
    links:
      - web
    volumes:
      - ./proxy/html:/usr/share/nginx/html
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - proxy
    volumes:
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
      - ./proxy/html:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email sergun-4@yandex.ru --agree-tos --no-eff-email --domain book.radio-set.ru --post-hook "touch /etc/letsencrypt/CERT_RENEWED" --test-cert
volumes:
  pg_data: {}
  pg_backups: {}
